/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Storefront": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "StorefrontApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "StorefrontRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
  }
}

import "sst"
export {}